name: ohbm_optimize
channels:
  - conda-forge
  - http://conda.anaconda.org/gurobi
dependencies:
  - python>=3.6
  - numpy
  - pandas
  - gurobi
  - matplotlib
  - pip
  - pip:
    - ortools
    - xlrd
  
